---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-debian12-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  env:
    MOLECULE_PROJECT_DIRECTORY: "extensions/molecule/opencode"
  inventory:
    group_vars:
      all:
        opencode_skip_configure: true
verifier:
  name: ansible
