---
cli_tools_installer: pkg
cli_tools_privilege_escalation: true

cli_tools_os_pkgs:
  - bat
  - btop
  - coreutils
  - eza
  - entr       # Run commands when files change
  - fastfetch  # System info display
  - fd
  - fzf
  - htop
  - jq
  - lazygit
  - mtr        # Network diagnostic tool
  - powerlevel10k  # Zsh theme
  - tree
  - watch      # Execute commands periodically
  - wget
  - zoxide

cli_tools_skip_install: false
