name: PR Check and Test

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  pr-check-and-test:
    uses: calavia-org/workflows-lib/.github/workflows/pr-check-and-test.yml@feat/split-test-add-prerelease
    with:
      technology: ansible
      run-pre-commit: true
      run-build: true
      run-unit-tests: true
      run-integration-tests: false
      run-package: true
      ansible-collection-path: collections/ansible_collections/calaviaorg/setup
      prerelease-enabled: false
      python-version: '3.12'
      tox-ini: tox-ansible.ini
      test-command: python -m tox --ansible -e unit-py3.12-2.20 --conf tox-ansible.ini
      fail-on-missing: false
      cache-enabled: true
      report-enabled: true
      comment-on-pr: false
      timeout-minutes: 30
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
