name: PR Check and Auto-Bump

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pr-check-and-bump:
    uses: calavia-org/workflows-lib/.github/workflows/pr-check-and-bump.yml@v0
    with:
      allowed-branch-pattern: ""
      allowed-target-branches: "main,release/*"
      version-file: "collections/ansible_collections/jcalavia_org/setup/galaxy.yml"
      fail-on-invalid-branch: false
      require-conventional-commits: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
