---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: darwin-instance
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_connection: local
        git_skip_configure: true
        gpg_skip_configure: true
        nvim_skip_configure: true
        tmux_tpm_enable: false
verifier:
  name: ansible
